# Generated by Django 6.0.1 on 2026-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
